#ifndef MYCOBOT_COMMANDS_H
#define MYCOBOT_COMMANDS_H

#include <cstdint>

namespace cobot {

enum command : std::uint8_t {
  // system status
  robot_version = 0x01,
  software_version = 0x02,
  get_robot_id = 0x03,
  set_robot_id = 0x04,
  get_error_info = 0x07,
  clear_error_info = 0x08,
  get_atom_version = 0x09,
  // overall status
  power_on = 0x10,
  power_off = 0x11,
  is_power_on = 0x12,
  release_all_servos = 0x13,
  is_controller_connected = 0x14,
  read_next_error = 0x15,
  set_fresh_mode = 0x16,
  get_fresh_mode = 0x17,
  set_free_mode = 0x1a,
  is_free_mode = 0x1b,
  cobotx_get_angle = 0x1c,
  cobotx_is_go_zero = 0x1d,
  focus_all_servos = 0x18,
  go_zero = 0x19,
  // mdi mode and operation
  get_angles = 0x20,
  send_angle = 0x21,
  send_angles = 0x22,
  get_coords = 0x23,
  send_coord = 0x24,
  send_coords = 0x25,
  pause = 0x26,
  is_paused = 0x27,
  resume = 0x28,
  stop = 0x29,
  is_in_position = 0x2a,
  is_moving = 0x2b,
  get_angle = 0x2c,
  get_coord = 0x2d,
  send_angles_auto = 0x2e,
  get_solution_angles = 0x2e,
  set_solution_angles = 0x2f,
  // jog mode and operation
  jog_angle = 0x30,
  jog_absolute = 0x31,
  jog_coord = 0x32,
  jog_increment = 0x33,
  jog_stop = 0x34,
  sethtsgrippertorque = 0x35,
  gethtsgrippertorque = 0x36,
  getgripperprotectcurrent = 0x37,
  initgripper = 0x38,
  setgripperprotectcurrent = 0x39,
  cobotx_get_solution_angles = 0x35,
  cobotx_set_solution_angles = 0x36,
  set_encoder = 0x3a,
  get_encoder = 0x3b,
  set_encoders = 0x3c,
  get_encoders = 0x3d,
  set_encoders_drag = 0x3e,
  // running status and settings
  get_speed = 0x40,
  set_speed = 0x41,
  get_feed_override = 0x42,
  get_acceleration = 0x44,
  set_acceleration = 0x45,
  get_joint_min_angle = 0x4a,
  get_joint_max_angle = 0x4b,
  set_joint_min = 0x4c,
  set_joint_max = 0x4d,
  // servo control
  is_servo_enable = 0x50,
  is_all_servo_enable = 0x51,
  set_servo_data = 0x52,
  get_servo_data = 0x53,
  set_servo_calibration = 0x54,
  joint_brake = 0x55,
  release_servo = 0x56,
  focus_servo = 0x57,
  // atom io
  set_pin_mode = 0x60,
  set_digital_output = 0x61,
  get_digital_input = 0x62,
  set_pwm_mode = 0x63,
  set_pwm_output = 0x64,
  get_gripper_value = 0x65,
  set_gripper_state = 0x66,
  set_gripper_value = 0x67,
  set_gripper_calibration = 0x68,
  is_gripper_moving = 0x69,
  set_color = 0x6a,
  set_gripper_torque = 0x6f,
  set_color_myarm = 0x70,
  set_eletric_gripper = 0x6b,
  init_eletric_gripper = 0x6c,
  set_gripper_mode = 0x6d,
  get_gripper_mode = 0x6e,
  mercury_drag_tech_save = 0x70,
  mercury_drag_tech_execute = 0x71,
  mercury_drag_tech_pause = 0x72,
  get_accei_data = 0x73,
  // coordinate transformation
  set_tool_reference = 0x81,
  get_tool_reference = 0x82,
  set_world_reference = 0x83,
  get_world_reference = 0x84,
  set_reference_frame = 0x85,
  get_reference_frame = 0x86,
  set_movement_type = 0x87,
  get_movement_type = 0x88,
  set_end_type = 0x89,
  get_end_type = 0x8a,
  write_move_c = 0x8c,
  // impact checking,
  set_joint_current = 0x90,
  get_joint_current = 0x91,
  set_current_state = 0x92,
  // basic,
  set_basic_output = 0xa0,
  get_basic_input = 0xa1,
  get_base_input = 0xa2,
  set_base_pwm = 0xa5,
  // linux gpio, mode: gpio.bcm,
  set_gpio_mode = 0xaa,
  set_gpio_up = 0xab,
  set_gpio_output = 0xac,
  get_gpio_in = 0xad,
  // set wifi,
  set_ssid_pwd = 0xb0,
  get_ssid_pwd = 0xb1,
  set_server_port = 0xb2,
  // get the measured distance,
  get_tof_distance = 0xc0,
  get_basic_version = 0xc1,
  set_communicate_mode = 0xc2,
  get_communicate_mode = 0xc3,
  // planning speed,
  get_plan_speed = 0xd0,
  get_plan_acceleration = 0xd1,
  set_plan_speed = 0xd2,
  set_plan_acceleration = 0xd3,
  move_round = 0xd4,
  get_angles_coords = 0xd5,
  get_quick_info = 0xd6,
  set_four_pieces_zero = 0xd7,
  // motor status read,
  get_servo_speed = 0xe1,
  get_servo_currents = 0xe2,
  get_servo_voltages = 0xe3,
  get_servo_status = 0xe4,
  get_servo_temps = 0xe5,
  get_servo_lastpdi = 0xe6,
  servo_restore = 0xe7,
  set_error_detect_mode = 0xe8,
  get_error_detect_mode = 0xe9,
  mercury_get_base_coords = 0xf0,
  mercury_set_base_coord = 0xf1,
  mercury_set_base_coords = 0xf2,
  mercury_jog_base_coord = 0xf3,
  get_base_coords = 0xf0,
  base_to_single_coords = 0xf1,
  collision = 0xf2,
  get_base_coord = 0xf3,
  get_all_base_coords = 0xf4,
  write_base_coord = 0xf5,
  write_base_coords = 0xf6,
  jog_inc_coord = 0xf7,
  collision_switch = 0xf8,
  is_collision_on = 0xf9
};

} // namespace cobot

#endif // MYCOBOT_COMMANDS_H
